
name: Docker Image CI

on:
  push:
    tags:
      - hello-spring deploy

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: CD hello spring
        run: cd hello-spring

      - name: Docker Hub Sign-in
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Building Docker Image
        run: docker build -t $REPO:latest -t $REPO:${GITHUB_RUN_ID} .

      - name: Publish Docker Image
        run: docker push $REPO
